---
- name: Creating MySQL user (medium_post)
  community.mysql.mysql_user:  
    name: "{{ db_user }}"  
    password: "{{ db_pass }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
    column_case_sensitive: false  

- name: Creating medium_db
  community.mysql.mysql_db:  
    name: "{{ db_name }}"
    state: present
